pattern_hi = r"Прив\w+|прив\w+|Здр\w+|доб\w+\s\w+|рад\w+|Рад\w+|здр\w+|Доб\w+|Hi|hi|hellow|Hellow"
pattern_yes = r"Да|да|ok|Ok|Yes|yes|ок|хоро\w+|Ага|ага|валяй|Валяй|Хорошо|давай|Давай\w+"
pattern_age_1 = r"(\d+-\d+)|(от\d+\до\d+)|(\d+\s\d+)|(\d+)|(от\s\d+\s\до\s\d+)"
pattern_age = r"(\d+-\d+)|(от(\d+)до(\d+))|(от\s(\d+)\s\до\s(\d+))|(\d+)"
pattern_gender_M = r"друга|Муж|муж\w+|муж|^м|^М|товар\w+|man|Man|male|the male|саме\w+"
pattern_gender_W = r"деву\w+|царев\w+|жен\w+|^ж|^Ж|wom\w+|^w|^W|подру\w+"